/**
 * Finds the extra character in string `t` that is not present in string `s`.
 * Assumes that `t` is generated by shuffling string `s` and adding one extra character at a random position.
 *
 * @param {string} s - The original string.
 * @param {string} t - The string with one extra character.
 * @returns {string|undefined} The extra character found in `t` that is not in `s`, or `undefined` if not found.
 *
 * @example
 * findTheDifference("abcd", "abcde"); // Returns 'e'
 * @example
 * findTheDifference("hello", "hlello"); // Returns 'l'
 */
var findTheDifference = function (s, t) {
  for (let i = 0; i < t.length; i++) {
    if (!s.includes(t[i])) {
      console.log(t[i]);
      return t[i];
    }
  }
};

findTheDifference("abcd", "abcdt");
